# Generated by Django 3.2.4 on 2021-08-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feed',
            field=models.TextField(max_length=200),
        ),
    ]
