# Generated by Django 3.2.4 on 2021-08-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_feedback_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
